name: CI/CD Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Critical for package discovery
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/unit/ -v
          pytest tests/integration/ -v
      - name: Generate coverage report
        run: |
          coverage run -m pytest
          coverage report -m
